version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    # specify the version you desire here
    - image: cimg/node:lts-browsers
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_TOKEN

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

orbs:
  codecov: codecov/codecov@1.1.6
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  test:
    <<: *defaults
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: 'package install'
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: yarn karma
      - run: sudo apt install lcov
      - run: find ./coverage  -name lcov.info -exec echo -a {} \; | xargs lcov -o ./coverage/merged-lcov.info
      - codecov/upload:
          file: ./coverage/merged-lcov.info

      - store_artifacts:
          path: ./coverage
          destination: coverage-report

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          context:
            - docker-hub-cred
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/

